// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdSeM28R-NcrTbDQgUaCtVCkBN-VeFKU',
    appId: '1:38924361590:web:4cec2486c4bc59a4082457',
    messagingSenderId: '38924361590',
    projectId: 'travels-lesson72',
    authDomain: 'travels-lesson72.firebaseapp.com',
    storageBucket: 'travels-lesson72.appspot.com',
    measurementId: 'G-L8DJ1C4TBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3wwXTbulPbJpwvdRgSYIDBCFIt3DWSqo',
    appId: '1:38924361590:android:1c130d0dc0868aca082457',
    messagingSenderId: '38924361590',
    projectId: 'travels-lesson72',
    storageBucket: 'travels-lesson72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZV12hGpjDk3QkkmfLnj9l0Ciqa2GF1I',
    appId: '1:38924361590:ios:4c48c01cd2a25457082457',
    messagingSenderId: '38924361590',
    projectId: 'travels-lesson72',
    storageBucket: 'travels-lesson72.appspot.com',
    iosBundleId: 'com.example.lesson72',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZV12hGpjDk3QkkmfLnj9l0Ciqa2GF1I',
    appId: '1:38924361590:ios:4c48c01cd2a25457082457',
    messagingSenderId: '38924361590',
    projectId: 'travels-lesson72',
    storageBucket: 'travels-lesson72.appspot.com',
    iosBundleId: 'com.example.lesson72',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvdSeM28R-NcrTbDQgUaCtVCkBN-VeFKU',
    appId: '1:38924361590:web:d1f3df6cb4b7bcd4082457',
    messagingSenderId: '38924361590',
    projectId: 'travels-lesson72',
    authDomain: 'travels-lesson72.firebaseapp.com',
    storageBucket: 'travels-lesson72.appspot.com',
    measurementId: 'G-WS7Y238VHP',
  );
}
